.TH capifaxrcvd 1 "01 June 2015" "man page"
.SH NAME
capifaxrcvd — a FAX receive daemon for CAPI
.SH SYNOPSIS
capifaxrcvd [-i stationID] [-h header] [-l listenNumber] [-n notifyCmd] rcvDirectory
.SH DESCRIPTION
capifaxrcvd is a daemon to receive faxes via CAPI; you need a CAPI capable ISDN card with the appropriate drivers.

The final argument must be the directory in which the received faxes are to be placed. The filenames of the received faxes are of the form:
f[fn]xxxtttttttt
[fn] indicates the resolution (fine or normal),
xxx indicated the number of pages,
tttttttt is the (hexadecimal) timestamp of the fax (seconds since the Unix epoch, 00:00 on January 1st, 1970 UTC).

The daemon will fork itself into the background.

This stuff is based heavily on AVM's CAPI-adk for linux.
.SH OPTIONS
.TP
-i station_ID
    the station ID. Typically the company name or similar.
.TP
-h headline
    title of sent document. (?)
.TP
-l listenNumber
    the phone number on which to receive faxes, i.e. the number to listen on.
.TP
-n notifyCmd
    command to execute when a fax has been received. It will be called with one argument, namely the filename of the received fax (without the directory name).
.SH AUTHOR
manpage written from C source by Paul Slootman <paul@debian.org>.
