.TH capifaxrcvd 1 "01 June 2015" "capifaxrcvd"
.SH NAME
capifaxrcvd
.SH SYNOPSIS
This executable is part of the package 'isdn4k-utils': CAPI 2.0 library
and associated tools. Documentation for a specific package may be available at
/usr/share/doc/isdn4k-utils
.SH DESCRIPTION
.PP
This package contains the CAPI 2.0 library, which is needed for all
CAPI applications. It also contains programs to show information about
installed CAPI controllers and for the receiving and sending of FAX
messages. CAPI 2.0 drivers for Linux are available for a growing number
of ISDN devices.
.SH AUTHOR
.EX
\&Carsten Paeth <calle@calle.in-berlin.de>
\&Kai Germaschewski <kai@tp1.ruhr-uni-bochum.de>
\&Armin Schindler <mac@melware.de>
\&Werner Cornelius <Cornelius@isdn-development.de>
\&Karsten Keil <kkeil@suse.de>
\&and more.
.BR
This manual page was written by Than Ngo <than@redhat.com>
