.TH capifax 1 "01 June 2015" "capifax"
.SH NAME
capifax - a FAX send application for CAPI
.SH SYNOPSIS
capifax [-v] [-i stationID] [-h header] [-c callerNumber] phone file
.SH DESCRIPTION
.PP
capifax is an application to send faxes via CAPI; you need a CAPI
capable ISDN card with the appropriate drivers.
The final argument must be the phone number of the receiving fax
machine.
This stuff is based heavily on AVM’s CAPI-adk for linux.
.SH OPTIONS
.TP
-v
Be verbose.
.TP
-c	callerNumber
the phone number used as the sender.
.TP
-i station_ID
the sender’s station ID. Typically the company name or  similar.
.TP
-h header
title of sent document.
.SH AUTHOR
This manual page was written by Paul Slootman <paul@tdebian.org>,
Than Ngo <than@redhat.com>

