.TH vboxcnvt 1 "01 June 2015" "vboxcnvt"
.SH NAME
vboxcnvt - isdn voice box (converter backend)
.SH DESCRIPTION
.PP
This is the real converter, the backend. Don’t call it directly; call
it by one of its other names: autovbox, rmdtovbox, vboxtoau or vboxmode.
.SH SEE ALSO
.TP
autovbox(1), rmdtovbox(1), vboxtoau(1), vboxmode(1), vbox(5)
.SH AUTHOR
This manual page was written by Paul Slootman <paul@tdebian.org>,
Than Ngo <than@redhat.com>
